<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- ========================================================================= -->
  <!-- Spring Boot parent -->
  <!-- ========================================================================= -->
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.1.0</version>
    <relativePath/>
  </parent>

  <!-- ========================================================================= -->
  <!-- Project metadata -->
  <!-- ========================================================================= -->
  <groupId>es.inditex</groupId>
  <artifactId>pricing-engine</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <name>pricing-engine</name>
  <description>Pricing Engine technical assessment</description>

  <!-- ========================================================================= -->
  <!-- Project properties -->
  <!-- ========================================================================= -->
  <properties>
    <!-- Encoding -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <!-- Java -->
    <java.version>21</java.version>
    <!-- Dependency versions -->
    <checkstyle.version>13.8.0</checkstyle.version>
    <springdoc.version>3.0.3</springdoc.version>
    <!-- Plugin versions -->
    <spotless.plugin.version>3.8.0</spotless.plugin.version>
    <checkstyle.plugin.version>3.6.0</checkstyle.plugin.version>
    <openapi-generator.plugin.version>7.24.0</openapi-generator.plugin.version>
  </properties>

  <!-- ========================================================================= -->
  <!-- Project dependencies -->
  <!-- ========================================================================= -->
  <dependencies>
    <!-- Common -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Web -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>

    <!-- Persistence -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-h2console</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-flyway</artifactId>
    </dependency>

    <!-- Documentation -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>${springdoc.version}</version>
    </dependency>

    <!-- Testing -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-resttestclient</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <!-- ========================================================================= -->
  <!-- Build configuration -->
  <!-- ========================================================================= -->
  <build>
    <plugins>
      <!-- Code formatting -->
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>${spotless.plugin.version}</version>
        <configuration>
          <java>
            <eclipse>
              <file>${project.basedir}/config/formatter.xml</file>
            </eclipse>
            <importOrder>
              <file>${project.basedir}/config/eclipse.importorder</file>
            </importOrder>
            <removeUnusedImports/>
            <trimTrailingWhitespace/>
            <endWithNewline/>
          </java>
          <pom>
            <sortPom/>
          </pom>
          <formats>
            <format>
              <includes>
                <include>.editorconfig</include>
                <include>.gitattributes</include>
                <include>.gitignore</include>
                <include>**/*.md</include>
                <include>**/*.xml</include>
                <include>**/*.yaml</include>
              </includes>
              <excludes>
                <exclude>target/**</exclude>
              </excludes>
              <trimTrailingWhitespace/>
              <endWithNewline/>
            </format>
          </formats>
        </configuration>
        <executions>
          <execution>
            <id>spotless-check</id>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Code quality -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>${checkstyle.plugin.version}</version>
        <configuration>
          <configLocation>${project.basedir}/config/checkstyle.xml</configLocation>
          <includeTestSourceDirectory>true</includeTestSourceDirectory>
          <consoleOutput>true</consoleOutput>
          <failOnViolation>true</failOnViolation>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>${checkstyle.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>checkstyle-check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>validate</phase>
          </execution>
        </executions>
      </plugin>

      <!-- Compilation -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>

      <!-- OpenAPI code generation -->
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>${openapi-generator.plugin.version}</version>
        <executions>
          <execution>
            <id>generate-openapi</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/static/openapi/pricing-api.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <apiPackage>es.inditex.pricingengine.infrastructure.inbound.rest.api</apiPackage>
              <modelPackage>es.inditex.pricingengine.infrastructure.inbound.rest.model</modelPackage>
              <generateApiDocumentation>false</generateApiDocumentation>
              <generateApiTests>false</generateApiTests>
              <generateModelDocumentation>false</generateModelDocumentation>
              <generateModelTests>false</generateModelTests>
              <generateSupportingFiles>true</generateSupportingFiles>
              <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
              <configOptions>
                <!-- Generation strategy -->
                <delegatePattern>true</delegatePattern>
                <!-- Java types -->
                <dateLibrary>java8-localdatetime</dateLibrary>
                <!-- Model generation -->
                <openApiNullable>false</openApiNullable>
                <!-- Spring generation -->
                <useSpringBoot4>true</useSpringBoot4>
                <useJackson3>true</useJackson3>
                <useTags>true</useTags>
                <!-- Documentation -->
                <documentationProvider>none</documentationProvider>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Unit tests -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <includes>
            <include>**/*Test.java</include>
          </includes>
          <excludes>
            <exclude>**/*IT.java</exclude>
          </excludes>
        </configuration>
      </plugin>

      <!-- Integration tests -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <includes>
            <include>**/*IT.java</include>
          </includes>
        </configuration>
        <executions>
          <execution>
            <id>integration-tests</id>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Spring Boot -->
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
