spring:
  application:
    name: pricing-engine
  datasource:
    url: jdbc:h2:mem:pricing
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    url: /openapi/pricing-api.yaml

logging:
  level:
    root: INFO
    es.inditex.pricingengine: INFO
