-- ============================================================================
-- Create prices table
-- ============================================================================
CREATE TABLE prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  price_list INTEGER NOT NULL,
  priority INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  curr VARCHAR(3) NOT NULL
);

-- ============================================================================
-- Optimize price lookup by brand, product and application date
-- ============================================================================
CREATE INDEX idx_prices_applicable
  ON prices (
    brand_id,
    product_id,
    start_date,
    end_date
  );
